"""initial tables

Revision ID: f714005b6873
Revises: 
Create Date: 2026-03-12 17:13:03.715912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f714005b6873'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rawg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metacritic_score', sa.Integer(), nullable=True),
    sa.Column('background_image', sa.String(length=500), nullable=True),
    sa.Column('released', sa.Date(), nullable=True),
    sa.Column('trailer_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rawg_id')
    )
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neon_user_id', sa.String(length=255), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neon_user_id', 'request_date')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neon_user_id', sa.String(length=255), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('parsed_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('openai_game_predict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filters_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('was_valid', sa.Boolean(), nullable=True),
    sa.Column('was_jailed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neon_user_id', sa.String(length=255), nullable=False),
    sa.Column('platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_metacritic', sa.Integer(), nullable=True),
    sa.Column('max_metacritic', sa.Integer(), nullable=True),
    sa.Column('release_year_min', sa.Integer(), nullable=True),
    sa.Column('release_year_max', sa.Integer(), nullable=True),
    sa.Column('multiplayer_pref', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neon_user_id')
    )
    op.create_table('user_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neon_user_id', sa.String(length=255), nullable=False),
    sa.Column('jail_count', sa.Integer(), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('banned_until', sa.DateTime(), nullable=True),
    sa.Column('last_violation_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neon_user_id')
    )
    op.create_table('game_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('store_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neon_user_id', sa.String(length=255), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neon_user_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_games')
    op.drop_table('recommendation_games')
    op.drop_table('game_tags')
    op.drop_table('game_stores')
    op.drop_table('game_genres')
    op.drop_table('user_violations')
    op.drop_table('user_preferences')
    op.drop_table('recommendations')
    op.drop_table('rate_limits')
    op.drop_table('games')
    # ### end Alembic commands ###
